### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by AlexWinder** [angelcamposm/ping#11]
In the documentation quick start it makes reference to the following:

```
use Acampos\Ping\Ping;
use Acampos\Ping\PingCommandBuilder;

// Create an instance of PingCommand
$command = (new PingCommandBuilder('192.168.1.1'));

// Pass the PingCommand instance to Ping and run...
$ping = (new Ping($command))->run();
```

However, the namespace of `Acampos` is incorrect, it should instead be `Acamposm`. I am happy to provide a pull request for this if required.

**Comment by angelcamposm** [comment]
oh, thanks, please, submit it. 😅

**Comment by angelcamposm** [comment]
solved :)

**Comment by AlexWinder** [comment]
Awesome! Sorry I hadn't yet had chance to create a PR.
