### ISSUE TITLE
Issue with format on Timer

### ISSUE THREAD

**Issue by simoebenhida** [angelcamposm/ping#13]
Any idea why $this->stop return a bool please?
```
Call to a member function format() on bool {"exception":"[object] (Error(code: 0): Call to a member function format() on bool at /websites/vv-api.ncic.com/vendor/acamposm/ping/src/Timer.php:96)
```

**Comment by angelcamposm** [comment]
Hi @simoebenhida i have isolated the code...

`$format = 'd-m-Y H:i:s.u';

$start = microtime(true);

$start_date = DateTime::createFromFormat('U.u', $start);

sleep(2);

$stop = microtime(true);

$stop_date = DateTime::createFromFormat('U.u', $stop);

$time_elapsed = $stop - $start;

return (object) [
    'start' => (object) [
        'as_float'       => $start,
        'human_readable' => $start_date->format($format),
    ],
    'stop' => (object) [
        'as_float'       => $stop,
        'human_readable' => $stop_date->format($format),
    ],
    'time' => (float) round($time_elapsed, 3, PHP_ROUND_HALF_DOWN),
];`

And for me works well, How is the environment where you are running it?
