### ISSUE TITLE
Undefined offset: -x on both Windows and Linux

### ISSUE THREAD

**Issue by iraqhub** [angelcamposm/ping#19]
AM trying to use this package in my project but i face problem in windows and Linux servers
I get Undefined offset: -2 in Linux Server ```vendor/acamposm/ping/src/Parsers/PingParserForLinux.php:24```

while getting Undefined offset: -1 ```vendor\acamposm\ping\src\Parsers\PingParserForWindows.php:137```

my sample code as Readme File 

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Acamposm\Ping\Ping;
use Acamposm\Ping\PingCommandBuilder;

class TestController extends Controller
{
    public function index()
    {
        $command = (new PingCommandBuilder('osama.app'));
        $ping = (new Ping($command))->run();
        dd($ping);
    }
}

```

**Comment by angelcamposm** [comment]
Hi @iraqhub i've implemented a test class to check if ping in windows throws that error... but it passes...

please check if in windows the result of ping -n 4 127.0.0.1 is similar to this (in spanish, english)

```bash
Haciendo ping a 127.0.0.1 con 32 bytes de datos:
Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128

Estadísticas de ping para 127.0.0.1:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 0ms, Máximo = 0ms, Media = 0ms
```

**Comment by angelcamposm** [comment]
Hi @iraqhub here you have the results of the tests...

PS C:\code\angelcamposm\ping> composer run test
> phpunit --colors=always --testdox
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.1
Configuration: C:\code\angelcamposm\ping\phpunit.xml
Warning:       No code coverage driver available

IPAddress (Acamposm\Ping\Tests\Unit\IPAddress)
 ✔ It require an IP address  22 ms
 ✔ It can validate an IPv4 addresses  1 ms
 ✔ It can validate an IPv6 addresses  1 ms
 ✔ It can detect an invalid IPv4 addresses  1 ms
 ✔ It can detect an invalid IPv6 addresses  1 ms
 ✔ It can detect an invalid ip address  1 ms

Ping Command Builder (Acamposm\Ping\Tests\Unit\PingCommandBuilder)
 ✔ It can create an ipv4 instance  91 ms
 ✔ Can get IPv4 command  6 ms
 ✔ Can get IPv6 command  5 ms
 ✔ Can get URL command  5 ms
 ✔ Can set count  6 ms
 ✔ Can not set a negative value to count  5 ms
 ✔ Can set interval  5 ms
 ✔ Can set packet size  5 ms
 ✔ Can set timeout  5 ms
 ✔ It can set ttl  5 ms
 ✔ It can not set ttl value greater than  5 ms

Timer (Acamposm\Ping\Tests\Unit\Timer)
 ✔ It can create a new instance  1 ms
 ✔ It can start the timer  1 ms
 ✔ It can stop the timer  1 ms
 ✔ It throws an exception  1 ms
 ✔ It returns an object  1 ms
 ✔ It stop the timer when get results  1 ms
 ✔ It get the same start value  1 ms
 ✔ It get the same stop value  1 ms

Ping (Acamposm\Ping\Tests\Feature\Ping)
 ✔ It can create a builder  5 ms
 ✔ It can make ping  4060 ms
 ✔ It can read host status from result  6 ms
 ✔ It can read raw from result  5 ms
 ✔ It can read options from result  5 ms

Time: 00:04.253, Memory: 20.00 MB

OK (30 tests, 32 assertions)

**Comment by iraqhub** [comment]
> Hi @iraqhub i've implemented a test class to check if ping in windows throws that error... but it passes...
> 
> please check if in windows the result of ping -n 4 127.0.0.1 is similar to this (in spanish, english)
> 
> ```shell
> Haciendo ping a 127.0.0.1 con 32 bytes de datos:
> Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
> Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
> Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
> Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
> 
> Estadísticas de ping para 127.0.0.1:
>     Paquetes: enviados = 4, recibidos = 4, perdidos = 0
>     (0% perdidos),
> Tiempos aproximados de ida y vuelta en milisegundos:
>     Mínimo = 0ms, Máximo = 0ms, Media = 0ms
> ```

I did ping on windows and results were fine

```
ping -n 4 127.0.0.1

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms


```

**Comment by iraqhub** [comment]
I think that error with my hosting , because they disabled ping function, Ive test it on my PC and its works fine , sorry for this .

**Comment by angelcamposm** [comment]
Normally the hosting providers disable ping function because using ports under 1024 requires root privileges...If you use, VPS it should work because you manage access and security.El 30 ene. 2022 19:52, iRAQ HUB ***@***.***> escribió:
I think that error with my hosting , because they disabled ping function, Ive test it on my PC and its works fine , sorry for this .
