### ISSUE TITLE
It works on cent os too?

### ISSUE THREAD

**Issue by Beatific-Angel** [angelcamposm/ping#20]
it works on cent os 7 too?

**Comment by angelcamposm** [comment]
yes, centos is the "free" RHEL :).

so, yes it must work.

**Comment by Beatific-Angel** [comment]
ok.
other question
I am using laravel 8.
Is it possible to integrate the ping module with laravel 8?

**Comment by angelcamposm** [comment]
Hi, yes you can integrate with laravel 8.
