### ISSUE TITLE
Ping module doesnt work

### ISSUE THREAD

**Issue by Beatific-Angel** [angelcamposm/ping#21]
![image](https://user-images.githubusercontent.com/64799935/159513061-bf2eef4f-ca9d-4fe6-b3a0-242cd54dbb28.png)

![image](https://user-images.githubusercontent.com/64799935/159513263-e27dac5b-77ee-4cef-8494-688531f3b8ec.png)

please check this image.
I wanted to show the result of the ping module.
but I can see the above error.

PingParserForWindows.php,
    private function parseStatistics(string $row): array
    {
         $ping_statistics = explode(', ', explode(':', $row)[1]);
     }
the $ping_statistic have empty value.

**Comment by Beatific-Angel** [comment]
this variable have value such as image.
![image](https://user-images.githubusercontent.com/64799935/159515395-58f8d469-29e3-4f88-af36-fa10f389c901.png)

exec($this->command->get(), $exec_result);
but $exec_result, this variable have not data after the command run.

**Comment by angelcamposm** [comment]
Hi @Beatific-Angel,

where are u running the command, i see windows, its locally? The class uses parsers so language is important thing to parse the output of the execution.

Have you tested to run the command in a cli?

regards.

**Comment by Beatific-Angel** [comment]
yes I am testing now in window.
it is local.
but my local have temp domain.

**Comment by Beatific-Angel** [comment]
you can help me?
I am busy due to this problem

**Comment by Beatific-Angel** [comment]
I checked the code carefully again.
it works on linux -- cent os 7.
but it doesnt work on window.
In linux, the result strcuture is same as you mentioned.
but in window part, the result part is not correct.
I think window part have problem.

**Comment by angelcamposm** [comment]
could you send me a sample of your ping command output from cli ?

i've tried it with english and spanish.

**Comment by Beatific-Angel** [comment]
![image](https://user-images.githubusercontent.com/64799935/160033295-78f2be9e-80cd-44c9-bf43-d02909a60f52.png)

**Comment by Beatific-Angel** [comment]
this ping command run on command prompt.
but in the laravel , after received the ping result, the parser can not analysis the result.
this is my think.

**Comment by angelcamposm** [comment]
no, i will say the output, not the command XD

for example:

ping 127.0.0.1

Haciendo ping a 127.0.0.1 con 32 bytes de datos:
Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128
Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128

Estadísticas de ping para 127.0.0.1:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 0ms, Máximo = 0ms, Media = 0ms

**Comment by SmoKE585** [comment]
I had the same issue. Do it:
`[root@localhost ~]# cat /etc/resolv.conf 
nameserver *router adr*
nameserver 8.8.8.8
nameserver 8.8.4.4
search localhost`

**Comment by angelcamposm** [comment]
@SmoKE585 hi its a shared hosting? or a VM?

Which OS is? Can you run regular ping command?
