### ISSUE TITLE
PHP Requirements non-specified

### ISSUE THREAD

**Issue by alaexala** [angelcamposm/ping#7]
What's the PHP requirements and extensions for this package? Im using Laravel 8, PHP 7.2 and Composer 2.0.7, didnt found any problems with other packages, maybe an old version?

![q5KbNkI](https://user-images.githubusercontent.com/62215039/103058348-34ee8f00-45a2-11eb-9e02-117fd08beb84.png)

Operating system | Ubuntu Linux 18.04.4
Kernel and CPU | Linux 4.15.0-128-generic on x86_64
Processor information | Intel(R) Xeon(R) CPU E5-2690 v3

root@ph:/var/www/sip.exala.es# apache2ctl -t -D DUMP_MODULES
Loaded Modules:
-  core_module (static)
-  so_module (static)
-  watchdog_module (static)
-  http_module (static)
-  log_config_module (static)
-  logio_module (static)
-  version_module (static)
-  unixd_module (static)
-  access_compat_module (shared)
-  alias_module (shared)
-  auth_basic_module (shared)
-  authn_core_module (shared)
-  authn_file_module (shared)
-  authz_core_module (shared)
-  authz_host_module (shared)
-  authz_user_module (shared)
-  autoindex_module (shared)
-  cache_module (shared)
-  deflate_module (shared)
-  dir_module (shared)
-  env_module (shared)
-  filter_module (shared)
-  mime_module (shared)
-  mpm_prefork_module (shared)
-  negotiation_module (shared)
-  php7_module (shared)
-  reqtimeout_module (shared)
-  rewrite_module (shared)
-  setenvif_module (shared)
-  socache_shmcb_module (shared)
-  ssl_module (shared)

**Comment by alaexala** [comment]
Added more information:

Composer version 2.0.7 2020-11-13 17:31:06

**Comment by cent89** [comment]
Hi, you have to use php 7.4.
See requirements in composer.json file.

**Comment by alaexala** [comment]
I'll upgrade to php 7.4 and will try again, i find this extension (your PING) very usefully for the project

**Comment by angelcamposm** [comment]
Hi, as cent89 replied, use php7.4. In the next version i'll update to php8.

**Comment by alaexala** [comment]
Hello,

It's any reason to update the requirements to PHP 8.0?, Any specific
function or something?

Best regards,
Exala Security,
Andre L.
